version: 1.0.{build}

environment:
  matrix:
    - os: Visual Studio 2015
      GENERATOR_NAME: "Visual Studio 14 2015"
# TODO: Uncomment when AppVeyor will provide XP toolchain for VS2017
#    - os: Visual Studio 2017
#      GENERATOR_NAME: "Visual Studio 15 2017"

clone_folder: c:\projects\xash\hlsdk-portable

build:
  project: build/INSTALL.vcxproj
  verbosity: normal

configuration:
  - Debug
  - Release

before_build:
  - git submodule update --init --recursive
  - cmake -G "%GENERATOR_NAME%" -B build -DCMAKE_INSTALL_PREFIX="dist"

artifacts:
  - path: dist
    name: hlsdk-msvc
    type: zip
