# Only for building testing version by Github CI workflow

name: Android apk CI(64bits only)

on:
  push:
    branches: [ "master" ]
    paths:
      #- 'idTech4Amm/**'
      #- 'Q3E/**'
      - '.github/workflows/android.yml'
      - '.github/workflows/android.changelog'
  pull_request:
    branches: [ "master" ]
    paths:
      #- 'idTech4Amm/**'
      #- 'Q3E/**'
      - '.github/workflows/android.yml'
      - '.github/workflows/android.changelog'

jobs:
  build-android:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup jdk 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'temurin'
        cache: gradle

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential # libtinfo5

    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew assembleRelease -Pabifilters=arm64-v8a

    - name: Rename APK
      id: rename_apk
      run: |
        apk_file=idTech4A++-testing-`date "+%Y_%m_%d-%H_%M_%S"`.apk
        cp ./idTech4Amm/build/outputs/apk/release/idTech4Amm-release.apk $apk_file
        echo "::set-output name=value::$apk_file"
      working-directory: ${{ github.workspace }}

    - name: Delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v1.1
      with:
        tag_name: android_testing
        delete_release: true
        repo: glKarin/com.n0n3m4.diii4a
        github_token: ${{ secrets.TOKEN }}

    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.TOKEN }}"
        automatic_release_tag: "android_testing"
        prerelease: true
        title: "Android testing (Non-release. Automatic CI builds)"
        files: |
          ${{ steps.rename_apk.outputs.value }}
